spring.application.name=taskmanager

taskmanager.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
taskmanager.app.jwtExpirationMs=86400000

spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=taskdb

server.port=8080

MONGO_URI=mongodb+srv://pavan1299_db_user:1299@cluster0.i0dxxtm.mongodb.net/taskmanager?retryWrites=true&w=majority

spring.jackson.mapper.accept-case-insensitive-enums=true